apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
      - name: task-tracker-container
        image: sravani28082003/task-tracker-app:latest
        ports:
        - containerPort: 8080
